# Generated by Django 4.0.1 on 2022-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('url', models.ImageField(blank=True, default='', null=True, upload_to='assets/img/')),
                ('format', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
