# Generated by Django 4.0.1 on 2022-01-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_alter_primertabla_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primertabla',
            old_name='edit',
            new_name='edited',
        ),
        migrations.AlterField(
            model_name='primertabla',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
